Adyen/adyen-java-api-library

- .travis.yml
- pom.xml
- src/main/java/com/adyen/Util/HMACValidator.java
- src/main/java/com/adyen/Util/Util.java
- src/main/java/com/adyen/service/HostedPaymentPages.java
- src/test/java/com/adyen/UtilTest.java
Reverted streams to support java 7
> Added HMAC validator

- src/main/java/com/adyen/Service.java
- src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
- src/main/java/com/adyen/notification/NotificationHandler.java
- src/main/java/com/adyen/service/HostedPaymentPages.java
- src/main/java/com/adyen/service/Modification.java
- src/main/java/com/adyen/service/Payment.java
- src/main/java/com/adyen/service/Recurring.java
- src/main/java/com/adyen/service/Resource.java
- src/test/java/com/adyen/GsonTest.java
- src/test/java/com/adyen/PaymentRequestBuilderTest.java
And it performs 3-4x faster to boot.
> Use static instances of Gson to improve performance. It's thread safe anyway.

- src/main/java/com/adyen/model/AbstractPaymentRequest.java
- src/test/java/com/adyen/PaymentRequestBuilderTest.java
> Change payment request -> metadata to Map <String, String>

- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/PaymentRequest.java
- src/main/java/com/adyen/service/resource/modification/Cancel.java
- src/main/java/com/adyen/service/resource/modification/CancelOrRefund.java
- src/main/java/com/adyen/service/resource/modification/Capture.java
- src/main/java/com/adyen/service/resource/modification/Refund.java
- src/main/java/com/adyen/service/resource/payment/Authorise.java
- src/main/java/com/adyen/service/resource/payment/Authorise3D.java
- src/main/java/com/adyen/service/resource/recurring/Disable.java
- src/main/java/com/adyen/service/resource/recurring/ListRecurringDetails.java
- src/test/java/com/adyen/PaymentRequestBuilderTest.java
Use v30 for Payments API
Payment request with recurringContractModel
Recurring: listRecurringDetails
> Use v30 for Payments API

- src/main/java/com/adyen/model/AbstractPaymentRequest.java
- src/main/java/com/adyen/model/PaymentRequest.java
Hide CSE token and card data from toString methods
Print additional data including CSE
> Hide CSE token and card data from toString methods

- src/main/java/com/adyen/constants/ApiConstants.java
- src/main/java/com/adyen/model/payout/ConfirmThirdPartyRequest.java
- src/main/java/com/adyen/model/payout/ConfirmThirdPartyResponse.java
- src/main/java/com/adyen/model/payout/DeclineThirdPartyRequest.java
- src/main/java/com/adyen/model/payout/DeclineThirdPartyResponse.java
- src/main/java/com/adyen/model/payout/ModifyRequest.java
- src/main/java/com/adyen/model/payout/ModifyResponse.java
- src/main/java/com/adyen/model/payout/StoreDetailAndSubmitRequest.java
- src/main/java/com/adyen/model/payout/StoreDetailAndSubmitResponse.java
- src/main/java/com/adyen/model/payout/StoreDetailRequest.java
- src/main/java/com/adyen/model/payout/StoreDetailResponse.java
- src/main/java/com/adyen/model/payout/SubmitRequest.java
- src/main/java/com/adyen/model/payout/SubmitResponse.java
- src/main/java/com/adyen/service/Payout.java
- src/main/java/com/adyen/service/resource/payout/ConfirmThirdParty.java
- src/main/java/com/adyen/service/resource/payout/DeclineThirdParty.java
- src/main/java/com/adyen/service/resource/payout/StoreDetail.java
- src/main/java/com/adyen/service/resource/payout/StoreDetailAndSubmitThirdParty.java
- src/main/java/com/adyen/service/resource/payout/SubmitThirdParty.java
- src/test/java/com/adyen/PayoutTest.java
- src/test/resources/mocks/payout/modifyResponse-success.json
- src/test/resources/mocks/payout/storeDetail-success.json
- src/test/resources/mocks/payout/storeDetailAndSubmitThirdParty-success.json
- src/test/resources/mocks/payout/submitResponse-success.json
payout api implementation
Tested Payout Endpoints based on Mocks.
> payout api implementation

- src/main/java/com/adyen/constants/ApiConstants.java
- src/main/java/com/adyen/model/AbstractPaymentRequest.java
- src/main/java/com/adyen/model/PaymentRequest.java
- src/test/java/com/adyen/PaymentRequestBuilderTest.java
Added helpers for secured fields requests
Authorisation request with secured fields data
> Secured Fields helpers

- src/main/java/com/adyen/service/HostedPaymentPages.java
> Shopper-locale optional (Directory Lookup)

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/service/resource/account/CloseAccount.java
- src/main/java/com/adyen/service/resource/account/CloseAccountHolder.java
- src/main/java/com/adyen/service/resource/account/CreateAccount.java
- src/main/java/com/adyen/service/resource/account/CreateAccountHolder.java
- src/main/java/com/adyen/service/resource/account/DeleteBankAccount.java
- src/main/java/com/adyen/service/resource/account/DeleteShareholder.java
- src/main/java/com/adyen/service/resource/account/GetAccountHolder.java
- src/main/java/com/adyen/service/resource/account/GetTierConfiguration.java
- src/main/java/com/adyen/service/resource/account/GetUploadedDocuments.java
- src/main/java/com/adyen/service/resource/account/SuspendAccountHolder.java
- src/main/java/com/adyen/service/resource/account/UnSuspendAccountHolder.java
- src/main/java/com/adyen/service/resource/account/UpdateAccount.java
- src/main/java/com/adyen/service/resource/account/UpdateAccountHolder.java
- src/main/java/com/adyen/service/resource/account/UpdateAccountHolderState.java
- src/main/java/com/adyen/service/resource/account/UploadDocument.java
- src/main/java/com/adyen/service/resource/fund/AccountHolderBalance.java
- src/main/java/com/adyen/service/resource/fund/AccountHolderTransactionList.java
- src/main/java/com/adyen/service/resource/fund/PayoutAccountHolder.java
- src/main/java/com/adyen/service/resource/fund/RefundNotPaidOutTransfers.java
- src/main/java/com/adyen/service/resource/fund/SetupBeneficiary.java
- src/main/java/com/adyen/service/resource/fund/TransferFunds.java
- src/main/java/com/adyen/service/resource/notification/CreateNotificationConfiguration.java
- src/main/java/com/adyen/service/resource/notification/DeleteNotificationConfigurations.java
- src/main/java/com/adyen/service/resource/notification/GetNotificationConfiguration.java
- src/main/java/com/adyen/service/resource/notification/GetNotificationConfigurationList.java
- src/main/java/com/adyen/service/resource/notification/TestNotificationConfiguration.java
- src/main/java/com/adyen/service/resource/notification/UpdateNotificationConfiguration.java
> Use v1 for MarketPay notification configuration API calls

- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/marketpay/Account.java
- src/main/java/com/adyen/model/marketpay/BusinessDetails.java
- src/main/java/com/adyen/model/marketpay/CreateAccountHolderRequest.java
- src/main/java/com/adyen/model/marketpay/CreateAccountHolderResponse.java
- src/main/java/com/adyen/model/marketpay/CreateAccountRequest.java
- src/main/java/com/adyen/model/marketpay/CreateAccountResponse.java
- src/main/java/com/adyen/model/marketpay/DocumentDetail.java
- src/main/java/com/adyen/model/marketpay/GetAccountHolderResponse.java
- src/main/java/com/adyen/model/marketpay/UpdateAccountHolderRequest.java
- src/main/java/com/adyen/model/marketpay/UpdateAccountHolderResponse.java
- src/main/java/com/adyen/model/marketpay/UpdateAccountResponse.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderVerificationContent.java
- src/main/java/com/adyen/model/marketpay/notification/GenericNotification.java
- src/main/java/com/adyen/model/marketpay/notification/KYCCheckSummary.java
updates to support v4 of marketpay account API
> PW-524 make changes for version v4 of account

- src/main/java/com/adyen/constants/HPPConstants.java
> Added merchantReturnData const

- src/main/java/com/adyen/service/Resource.java
Add handling for non-json API responses (403)
Valid/Invalid api key
> Add handling for non-json API responses (403)

- src/main/java/com/adyen/model/modification/ModificationResult.java
- src/test/java/com/adyen/ModificationTest.java
- src/test/resources/mocks/capture-success.json
Changed deserialization of additionalData modification responses to Map<String, String>
Capture
> Changed deserialization of additionalData modification responses

- src/main/java/com/adyen/Client.java
Adding Deprecated tag to setEnvironment method
> Adding Deprecated tag to setEnvironment method

- docs/install-library.html
- docs/using-library.html
> [PW-689] setEnvironment instructions and library version update

- src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java
> [PW-881]: Added equals and hashcode methods

- docs/checkout-api.html
> documentation change to reflect PaymentMethodContainer changes.

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
> [PW-1090]: Added response codes for 3DS 2.0

- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
Relates to [issue 154](https://github.com/Adyen/adyen-java-api-library/issues/154)
> Add pending result code

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
> Added new setter method for origin.

- src/main/java/com/adyen/constants/ApiConstants.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
- src/main/java/com/adyen/model/modification/AdjustAuthorisationRequest.java
> Add additionaldata properties for multibanco

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
Now, storeDetails param can be added to the creditCard / encryptedCreditCard request methods
It have been tests with 2 methods in order to get the recurring token
> store details param added to credit card details methods

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
> Added new field authentication in PaymentsResponse for 3DS2 responses

- src/main/java/com/adyen/model/checkout/PaymentsDetailsRequest.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
> 3DS setters added and authcode setter corrected.

- src/main/java/com/adyen/model/PaymentResult.java
Fixes [#163](https://github.com/Adyen/adyen-java-api-library/issues/163)
> Add missing enums for 3DS2

- src/main/java/com/adyen/model/modification/AbstractModificationRequest.java
Add application info in ToString method for AbstractModificationRequest
**Fixed issue**:  #179
> Add application info in ToString method for AbstractModificationRequest

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
- src/test/java/com/adyen/CheckoutTest.java
#183  BugFix Multibanco Null check added
> Release 2.1.0

- src/main/java/com/adyen/constants/ApiConstants.java
> [PW-1096] Added constants required for 3DS2

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/test/java/com/adyen/CheckoutTest.java
> RecurringProcessingModel field and enums addition

- src/main/java/com/adyen/model/PaymentRequest.java
> [PW-1289] Added missing Enum value UnscheduledCardOnFile

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
Added fields that were missing according to the [docs](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v41/payments)
> [PW-1312] Adding missing fields on Checkout PaymentsRequest

- pom.xml
- src/main/java/com/adyen/model/AccountInfo.java
- src/main/java/com/adyen/serializer/DateTimeISO8601Serializer.java
- src/test/java/com/adyen/serializer/DateTimeISO8601SerializerTest.java
> Fixed date to ISO8601 format serialization for AccountInfo

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
> Revert field allowedPaymentMethods removal, set to @Deprecated instead

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
BrowserInfo object added to toString method
**Fixed issue**:  #218
> PaymentsRequest browserInfo printed in toString method

- src/main/java/com/adyen/model/ThreeDS2RequestData.java
> Added merchantName to ThreeDS2RequestData

- src/main/java/com/adyen/model/nexo/PaymentInstrumentData.java
> Adding missing fields on PaymentInstrumentData

- src/main/java/com/adyen/model/nexo/CardAcquisitionTransaction.java
- src/main/java/com/adyen/model/nexo/CardReaderInitRequest.java
- src/main/java/com/adyen/model/nexo/CheckData.java
- src/main/java/com/adyen/model/nexo/Instalment.java
- src/main/java/com/adyen/model/nexo/ObjectFactory.java
- src/main/java/com/adyen/model/nexo/TransactionConditions.java
> Fix ForceEntryMode fields / Instalment and CheckData field names

- src/main/java/com/adyen/Util/Util.java
- src/test/java/com/adyen/UtilTest.java
https://docs.adyen.com/development-resources/currency-codes/
> Update currency code list

- src/main/java/com/adyen/model/nexo/AuthenticationMethodType.java
- src/main/java/com/adyen/terminal/serialization/XMLEnumAdapterFactory.java
- src/main/java/com/adyen/terminal/serialization/XMLEnumTypeAdapter.java
- src/test/java/com/adyen/serializer/XMLEnumSerializerTest.java
Handling both "On**L**inePIN", "On**l**inePIN"
> [PW-1398] Fix AuthenticationMethodType.OnlinePIN

- src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
- src/main/java/com/adyen/terminal/security/TerminalCommonNameValidator.java
- src/test/java/com/adyen/terminal/security/TerminalCommonNameValidatorTest.java
Validation on certificate CN for two cases:
C1) legacy-terminal-certificate.[environment].terminal.adyen.com
C2) [model-S/N].[environment].terminal.adyen.com
> [PW-1568] Terminal API certificate CN validation

- src/main/java/com/adyen/model/checkout/PaymentResultResponse.java
> Adding missing fields to PaymentResultResponse

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/PaymentResult.java
- src/main/java/com/adyen/model/checkout/PaymentResultResponse.java
#243 Add resultCode AuthenticationNotRequired
> Release version 2.6.1

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/nexo/ReversalRequest.java
> Added SaleData to ReversalRequest (#258)

- src/main/java/com/adyen/model/ThreeDSecureData.java
- src/main/java/com/adyen/model/checkout/ThreeDSecureData.java
> Added missing values to DirectoryResponseEnum

- src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java
> Added missing fields for Apple Pay and Google Pay token

- src/main/java/com/adyen/Service.java
- src/test/java/com/adyen/service/CheckoutTest.java
> [PW-1790] Fixed GSON html escaping on serialization

- .github/CODEOWNERS
- CONTRIBUTING.md
- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/Service.java
- src/main/java/com/adyen/model/ThreeDSecureData.java
- src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java
- src/main/java/com/adyen/model/checkout/ThreeDSecureData.java
- src/test/java/com/adyen/service/CheckoutTest.java
Fixed GSON html escaping on serialization (#266)
Added missing values to DirectoryResponseEnum (#267)
Added missing fields for Apple Pay and Google Pay token (#269)
**Fixed issue**:  #262 #265
> Release version 2.7.2

- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
> [PW-1792]: Add missing field selectedBrand

- src/main/java/com/adyen/constants/ApiConstants.java
- src/main/java/com/adyen/model/checkout/CheckoutPaymentsAction.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/resources/mocks/checkout/paymentsresult-multibanco-succes.json
> [PW-1792]:Multibanco update and Entity field addition

- src/main/java/com/adyen/service/exception/ApiException.java
- src/test/java/com/adyen/CheckoutTest.java
> PW-2034 Refactor ApiException, add unit test

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/service/Checkout.java
- src/main/java/com/adyen/service/Resource.java
- src/main/java/com/adyen/service/exception/ApiException.java
- src/test/java/com/adyen/CheckoutTest.java
- upgrade_release_version.sh
#288 [PW-2034] Add http response headers to ApiException 
#287 Support RequestOptions for /payments/details in Checkout
#278 Update issue templates
**Fixed issue**:  #284
> Release version 4.1.0 

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/enums/Gender.java
- src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java
- src/main/java/com/adyen/model/checkout/PersonalDetails.java
- src/main/java/com/adyen/model/nexo/BarcodeType.java
- src/main/java/com/adyen/model/nexo/OutputBarcode.java
- src/test/java/com/adyen/BaseTest.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/java/com/adyen/PaymentRequestTest.java
Java API Library 4.20 Release
Update BarcodeOuput to reflect API doc
PW-2114 Added "storedPaymentMethodId" to DefaultPaymentMethodDetails
PW-2090 Add AfterPay properties to the DefaultPaymentMethod
PW-2090
PW-2114
> Version Update 4.2.0

- src/main/java/com/adyen/model/PaymentResult.java
Updated possible resultcode values according to Adyen docs: https://docs.adyen.com/api-explorer/#/Payment/v52/authorise__resParam_resultCode
**Fixed issue**:  #327
> Updated PaymentResult.ResultCodeEnum possible values

- src/main/java/com/adyen/httpclient/HTTPClientException.java
- src/main/java/com/adyen/model/checkout/InputDetail.java
- src/main/java/com/adyen/model/checkout/PaymentMethod.java
- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/main/java/com/adyen/model/checkout/RecurringDetail.java
- src/main/java/com/adyen/model/checkout/Redirect.java
- src/main/java/com/adyen/model/checkoututility/OriginKeysResponse.java
- src/main/java/com/adyen/model/modification/AbstractModificationRequest.java
- src/main/java/com/adyen/model/nexo/SaleData.java
- src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
- src/main/java/com/adyen/service/HostedPaymentPages.java
- src/main/java/com/adyen/service/Payout.java
- src/main/java/com/adyen/service/Recurring.java
- src/main/java/com/adyen/service/Resource.java
- src/main/java/com/adyen/service/resource/checkout/PaymentMethods.java
- src/main/java/com/adyen/service/resource/checkout/PaymentsResult.java
- src/main/java/com/adyen/service/resource/checkoututility/OriginKeys.java
- src/main/java/com/adyen/service/resource/notification/CreateNotificationConfiguration.java
- src/main/java/com/adyen/service/resource/notification/DeleteNotificationConfigurations.java
- src/main/java/com/adyen/service/resource/notification/GetNotificationConfiguration.java
- src/main/java/com/adyen/service/resource/notification/UpdateNotificationConfiguration.java
Small code improvements
No additional tests needed since no logic has changed.
**Fixed issue**
This change is not related to any created Github Issue
> Improve minor code changes

- src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
accept all 20x resultcodes
/transferFunds call returning 202
> PW-2291: accept all 20x resultcodes

- src/main/java/com/adyen/model/nexo/LoyaltyAccountID.java
- src/main/java/com/adyen/model/nexo/OutputBarcode.java
- src/main/java/com/adyen/model/nexo/OutputText.java
- src/main/java/com/adyen/model/nexo/SoundContent.java
- src/main/java/com/adyen/model/nexo/StoredValueAccountID.java
- src/main/java/com/adyen/model/nexo/TrackData.java
changed the structure of the xsd file where classes with <xs:extension base="TextString"> were generating an incorrect "value" field, this has been replaced with the correct value from nexo document
> PW-1674: remove "value" and add correct value field according to nexo

- src/main/java/com/adyen/model/recurring/Recurring.java
> add EXTERNAL property

- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/AbstractPaymentRequest.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
> [PW-2079] Update checkout and payment service from v51 to v52

- .github/CODEOWNERS
- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/AbstractPaymentRequest.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
#341 Update checkout and payment service from v51 to v52
**Fixed issue**:  PW-2079
> Release 6.1.0

- src/main/java/com/adyen/model/nexo/Input.java
- src/test/java/com/adyen/TerminalCloudAPITest.java
- src/test/resources/mocks/terminal-api/input-request-success.json
Change MenuEntryMenuEntry to array
Added test with an example response for a InputRequest
> [PW-2297] Fix MenuEntryNumber

- src/main/java/com/adyen/model/modification/DonationRequest.java
- src/main/java/com/adyen/model/modification/ModificationResult.java
- src/main/java/com/adyen/service/Modification.java
- src/main/java/com/adyen/service/resource/modification/Donate.java
- src/test/java/com/adyen/BaseTest.java
- src/test/java/com/adyen/ModificationTest.java
- src/test/resources/mocks/donate-success.json
> PW-2405: add support for /donate

- src/main/java/com/adyen/model/ApiError.java
- src/main/java/com/adyen/service/Account.java
- src/main/java/com/adyen/service/Fund.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/fund/transfer-funds-error-invalid-fields.json
> PW-2300: add InvalidFields in ApiError

- src/main/java/com/adyen/model/notification/NotificationRequestItem.java
- src/test/java/com/adyen/NotificationTest.java
- src/test/resources/mocks/notification/offer-closed.json
Added event codes listed under Additional Configuration:
https://docs.adyen.com/development-resources/webhooks/understand-notifications#additional-configuration
> PW-2080: Add webhooks event codes for additional configuration

- .github/dependabot.yml
- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/checkout/CheckoutCancelOrderRequest.java
- src/main/java/com/adyen/model/checkout/CheckoutCancelOrderResponse.java
- src/main/java/com/adyen/model/checkout/CheckoutCreateOrderRequest.java
- src/main/java/com/adyen/model/checkout/CheckoutCreateOrderResponse.java
- src/main/java/com/adyen/model/checkout/CheckoutOrderResponse.java
- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
- src/main/java/com/adyen/model/modification/ModificationResult.java
- src/main/java/com/adyen/service/Checkout.java
- src/main/java/com/adyen/service/resource/checkout/Orders.java
- src/main/java/com/adyen/service/resource/checkout/OrdersCancel.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/java/com/adyen/ModificationTest.java
- src/test/resources/mocks/checkout/orders-cancel-success.json
- src/test/resources/mocks/checkout/orders-success.json
- src/test/resources/mocks/checkout/payments-success-order.json
**Important Notes**
- This is a major release, because we are introducing some backwards compatibility breaking changes in the following pull request:
#375 'response' field type changed to String for these operations:
/adjustAuthorisation
/cancel
/cancelOrRefund
/capture
/donate
/refund
/technicalCancel
/voidPendingRefund
- #368 added support for /orders and /ordersCancel for Checkout service
> Release 8.0.0

- src/main/java/com/adyen/terminal/security/NexoCrypto.java
- src/main/java/com/adyen/terminal/serialization/ByteArrayToBase64TypeAdapter.java
> fix: base64 not working with older versions of apache common

- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/Config.java
- src/main/java/com/adyen/model/posterminalmanagement/Address.java
- src/main/java/com/adyen/model/posterminalmanagement/AssignTerminalsRequest.java
- src/main/java/com/adyen/model/posterminalmanagement/AssignTerminalsResponse.java
- src/main/java/com/adyen/model/posterminalmanagement/FindTerminalRequest.java
- src/main/java/com/adyen/model/posterminalmanagement/FindTerminalResponse.java
- src/main/java/com/adyen/model/posterminalmanagement/GetStoresUnderAccountRequest.java
- src/main/java/com/adyen/model/posterminalmanagement/GetStoresUnderAccountResponse.java
- src/main/java/com/adyen/model/posterminalmanagement/GetTerminalDetailsRequest.java
- src/main/java/com/adyen/model/posterminalmanagement/GetTerminalDetailsResponse.java
- src/main/java/com/adyen/model/posterminalmanagement/GetTerminalsUnderAccountRequest.java
- src/main/java/com/adyen/model/posterminalmanagement/GetTerminalsUnderAccountResponse.java
- src/main/java/com/adyen/model/posterminalmanagement/MerchantAccount.java
- src/main/java/com/adyen/model/posterminalmanagement/Store.java
- src/main/java/com/adyen/service/PosTerminalManagement.java
- src/main/java/com/adyen/service/resource/posterminalmanagement/AssignTerminals.java
- src/main/java/com/adyen/service/resource/posterminalmanagement/FindTerminal.java
- src/main/java/com/adyen/service/resource/posterminalmanagement/GetStoresUnderAccount.java
- src/main/java/com/adyen/service/resource/posterminalmanagement/GetTerminalDetails.java
- src/main/java/com/adyen/service/resource/posterminalmanagement/GetTerminalsUnderAccount.java
- src/test/java/com/adyen/PosTerminalManagementTest.java
- src/test/resources/mocks/posterminalmanagement/assign-terminals-success.json
- src/test/resources/mocks/posterminalmanagement/find-terminal-success.json
- src/test/resources/mocks/posterminalmanagement/get-stores-under-account-success.json
- src/test/resources/mocks/posterminalmanagement/get-terminal-details-success.json
- src/test/resources/mocks/posterminalmanagement/get-terminals-under-account-success.json
added:
/assignTerminals
/findTerminal
/getTerminalsUnderAccount
​/getStoresUnderAccount
​/getTerminalDetails
https://docs.adyen.com/api-explorer/#/postfmapi/v1/overview
> PW 2353 Add pos terminal management endpoints

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/hop/GetOnboardingUrlRequest.java
- src/main/java/com/adyen/model/hop/GetOnboardingUrlResponse.java
- src/main/java/com/adyen/service/Hop.java
- src/main/java/com/adyen/service/resource/hop/GetOnboardingUrl.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/hop/get-onboarding-url-success.json
#397 Added HOP service: https://docs.adyen.com/api-explorer/#/Hop/v6/overview
> Release 8.2.0

- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/checkout/details/AmazonPayDetails.java
- src/main/java/com/adyen/model/checkout/details/AndroidPayDetails.java
- src/main/java/com/adyen/model/checkout/details/BillDeskOnlineDetails.java
- src/main/java/com/adyen/model/checkout/details/BillDeskWalletDetails.java
- src/main/java/com/adyen/model/checkout/details/BilldeskWalletDetails.java
- src/main/java/com/adyen/model/checkout/details/DokuDetails.java
- src/main/java/com/adyen/model/checkout/details/KlarnaDetails.java
- src/main/java/com/adyen/model/checkout/details/MasterpassDetails.java
- src/main/java/com/adyen/model/checkout/details/MobilePayDetails.java
- src/main/java/com/adyen/model/checkout/details/PayPalDetails.java
- src/main/java/com/adyen/model/checkout/details/PayUUpiDetails.java
- src/main/java/com/adyen/model/checkout/details/WeChatPayDetails.java
- src/main/java/com/adyen/model/checkout/details/WeChatPayMiniProgramDetails.java
- src/test/java/com/adyen/CheckoutTest.java
Checkout API is updated to v64, new payment details and fields has been added.
> PW-2807 Upgraded checkout API to v64 and added missing classes and fields

- src/main/java/com/adyen/model/checkout/PaymentMethodsResponse.java
- src/main/java/com/adyen/model/checkout/RedirectUrls.java
- src/main/java/com/adyen/model/checkout/TokenConnectIssuer.java
- src/main/java/com/adyen/model/checkout/TokenConnectStoringMethod.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/resources/mocks/checkout/paymentmethods-storingmethods-success.json
PW-2971 Adding storingMethods in PaymentMethodsResponse
> PW-2971 Added storingMethods in PaymentMethodsResponse

- src/main/java/com/adyen/model/checkout/PaymentMethodsRequest.java
Added order and splitCardFundingSources to PaymentMethodsRequest
Just used existing test scenario since we are not using any fields except merchantAccount
> PW-3018 Added order and splitCardFundingSources to PaymentMethodsRequest

- src/main/java/com/adyen/model/checkout/CreateStoredPaymentMethodRequest.java
- src/main/java/com/adyen/model/checkout/StoredPaymentMethodResource.java
- src/main/java/com/adyen/model/checkout/StoringMethod.java
- src/main/java/com/adyen/service/Checkout.java
- src/main/java/com/adyen/service/resource/checkout/StoredPaymentsMethods.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/resources/mocks/checkout/storedpaymentmethods-error-invalid-data-422.json
- src/test/resources/mocks/checkout/storedpaymentmethods-success.json
added /storedPaymentMethods support
Happy case in e2e tests and serialization tests in the library
**Fixed issue**:   PW-2972
> PW-2972 Added /storedPaymentMethods support

- src/main/java/com/adyen/model/checkout/details/BacsDirectDebitDetails.java
- src/test/java/com/adyen/CheckoutTest.java
Add BACS payment method.
A successful payment was created which resulted in a response with a correct redirect url. This URL could be used to further enter the info to complete the payment.
**Fixed issue**:  PW-3214
> FOC-PW-3214 Add bacs payment method

- src/main/java/com/adyen/service/BinLookup.java
> fix naming

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/Config.java
- src/main/java/com/adyen/model/SubjectErasureRequest.java
- src/main/java/com/adyen/model/SubjectErasureResponse.java
- src/main/java/com/adyen/service/DataProtection.java
- src/main/java/com/adyen/service/resource/dataprotection/RequestSubjectErasure.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/java/com/adyen/DataProtectionServiceTest.java
- src/test/resources/mocks/request-subject-erasure-not-found.json
- src/test/resources/mocks/request-subject-erasure-success.json
Add data protection subject erasure
From postman a "PAYMENT_NOT_FOUND" scenario was executed with result HTTP status 200 
**Fixed issue**:  pw-2888
> Add data protection service pw 2888

- src/main/java/com/adyen/model/checkout/LineItem.java
- src/test/java/com/adyen/BaseTest.java
- src/test/java/com/adyen/PaymentRequestTest.java
Add productUrl and imageUrl to LineItem class
The payment from postman is accepted in test environment.
> [PW-3275] Add productUrl and imageUrl to LineItem class

- src/main/java/com/adyen/model/Split.java
- src/main/java/com/adyen/model/checkout/CreatePaymentLinkRequest.java
- src/main/java/com/adyen/model/checkout/RiskData.java
Updated CreatePaymentLinkRequest model with checkout specs v66
Create payment link with new fields
> PW-2889 Updated CreatePaymentLinkRequest model with checkout specs v66

- src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
- src/test/java/com/adyen/serializer/SaleToAcquirerDataSerializerTest.java
Added authorisationType field in SaleToAcquirerData for Terminal API
Serialization test for SaleToAcquirerData
> PW-3365 Added authorisationType field in SaleToAcquirerData

- src/main/java/com/adyen/model/hop/GetOnboardingUrlRequest.java
- src/test/java/com/adyen/MarketPayTest.java
missing shopperLocale from GetOnboardingUrlRequest
**Fixed issue**: #461
> PW-3451 Add shopperLocale to GetOnboardingUrlRequest, fixes #461

- pom.xml
- src/main/java/com/adyen/deserializer/PaymentMethodDetailsDeserializerJackson.java
- src/main/java/com/adyen/deserializer/PaymentMethodDetailsTypeAdapter.java
- src/main/java/com/adyen/model/Amount.java
- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/main/java/com/adyen/model/checkout/details/AndroidPayDetails.java
- src/main/java/com/adyen/model/checkout/details/MasterpassDetails.java
- src/main/java/com/adyen/model/checkout/details/MobilePayDetails.java
- src/main/java/com/adyen/model/checkout/details/PayUUpiDetails.java
- src/main/java/com/adyen/model/checkout/details/WeChatPayDetails.java
- src/main/java/com/adyen/model/checkout/details/WeChatPayMiniProgramDetails.java
- src/test/java/com/adyen/BaseTest.java
- src/test/java/com/adyen/CheckoutTest.java
Added custom Gson and Jackson deserializer for PaymentMethodDetails based on the `type` field.
All PaymentDetails models.
#369 #377 #415
> PW-2557 Custom deserializer for PaymentMethodDetails

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/deserializer/PaymentMethodDetailsDeserializerJackson.java
bugfix release for missing storedpaymentmethodid getter/setter in PayPalDetails #473
> Release 11.0.1

- src/main/java/com/adyen/model/notification/NotificationRequest.java
- src/test/java/com/adyen/NotificationTest.java
Fixed Jackson serialization issue for Notification request.
GSON and Jackson serialization
**Fixed issue**:  #476
> PW-3686 Fixed Jackson serialization of NotificationRequest

- pom.xml
Removed unused **javax.xml.crypto:jsr105-api** dependency which had potential vulnerability.
e2e tests
**Fixed issue**:  #453
> PW-3706 Removed unused dependency which had potential vulnerability

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
Major release for breaking change in Terminal Local API(changed encoding from ASCII to UTF_8)
> Release 12.0.0

- src/main/java/com/adyen/model/marketpay/DocumentDetail.java
Added values missing according to api-specs
> PW-3901 - Add missing values to DocumentDetail.DocumentTypeEnum

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/model/marketpay/DocumentDetail.java
#493  Added missing enum values to DocumentDetail.DocumentTypeEnum
> Release version 12.0.1

- src/main/java/com/adyen/model/checkout/CheckoutPaymentsAction.java
- src/test/java/com/adyen/CheckoutTest.java
- src/test/resources/mocks/checkout/payments-banktransfer-success.json
BankTransfer fields were missing in the CheckoutPaymentsAction class.
> PW-4494: Add BankTransfer fields to the CheckoutPaymentsAction class

- src/main/java/com/adyen/util/HMACValidator.java
Added time invariant implementation of validateHMAC.
> Added time invariant implementation of validateHMAC.

- src/main/java/com/adyen/model/marketpay/AccountHolderStatus.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/account/get-individual-account-holder-success.json
fixed field
`accountEvent` -> `event`
**Fixed issue**: #521
> PW-4556: fix AccountHolderStatus

- src/main/java/com/adyen/model/checkout/PaymentsResponse.java
fix toString method in paymentsResponse
**Fixed issue**:  #526
> PW-4578 fix toString method, fixes #526

- src/main/java/com/adyen/model/PaymentRequest.java
- src/main/java/com/adyen/model/checkout/Mandate.java
- src/main/java/com/adyen/model/checkout/PaymentsRequest.java
- src/main/java/com/adyen/model/recurring/NotifyShopperRequest.java
- src/main/java/com/adyen/model/recurring/NotifyShopperResult.java
- src/main/java/com/adyen/service/Recurring.java
- src/main/java/com/adyen/service/resource/recurring/NotifyShopper.java
- src/test/java/com/adyen/RecurringTest.java
- src/test/resources/mocks/recurring/notifyShopper-success.json
- added new endpoint in `Recurring` service: `/notifyShopper`
- added missing field in `Checkout` `/payments` request: `mandate`
> PW-4436 add notifyShopper endpoint and mandate field

- src/main/java/com/adyen/model/marketpay/BusinessDetails.java
- src/main/java/com/adyen/model/marketpay/Signatory.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/account/get-business-account-holder-success.json
Just adding signatories for [2021 KYC Updates](https://docs.adyen.com/platforms/onboarding-and-verification/kyc-requirements-update#signatories)
**Fixed issue**:  none
> Adding signatories to BusinessDetails

- src/main/java/com/adyen/model/marketpay/AccountEventContainer.java
- src/main/java/com/adyen/model/marketpay/AccountHolderStatus.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/account/get-individual-account-holder-success.json
> Add AccountEventContainer layer for AccountHolderStatus, fixes #529

- src/main/java/com/adyen/util/HMACValidator.java
- src/test/java/com/adyen/util/HMACValidatorTest.java
Fixed NPE in `validateHMAC`
#554
> Fixed NPE in validateHMAC

- README.md
- pom.xml
- src/main/java/com/adyen/httpclient/AdyenHttpClient.java
- src/main/java/com/adyen/httpclient/AdyenResponseHandler.java
Updated Apache HTTP Client to version 5.1 to avoid package conflict in Android. 
Updated documentation for proxy setting.
E2E tests including client certificate authentication.
> PW-4936 Updated Apache HTTP Client to version 5.1 to avoid package conflict in Android

- src/main/java/com/adyen/model/marketpay/GetTaxFormRequest.java
- src/main/java/com/adyen/model/marketpay/GetTaxFormResponse.java
- src/main/java/com/adyen/service/Account.java
- src/main/java/com/adyen/service/resource/account/GetTaxForm.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/resources/mocks/marketpay/account/get-tax-form-success.json
added [getTaxForm](https://docs.adyen.com/api-explorer/#/Account/v6/post/getTaxForm) endpoint
Unit test only, as the endpoint is not supposed to work on TEST
> PW-4609 add /getTaxForm endpoint

- src/main/java/com/adyen/terminal/security/NexoCrypto.java
fixed a small issue with HMAC comparison.
> fixed issue with HMAC comparison

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
> bump version for release

- README.md
- pom.xml
> bump version in readme and pom

- pom.xml
- src/main/java/com/adyen/model/nexo/Input.java
fix javadoc errors due to bug in java
> fix javadoc errors due to bug in java

- .github/workflows/javaci.yml
Add github action file
Add the file to run the tests on github actions
> [PW-5250] Create javaci.yml

- src/main/java/com/adyen/deserializer/PaymentMethodDetailsDeserializerJackson.java
- src/main/java/com/adyen/deserializer/PaymentMethodDetailsTypeAdapter.java
- src/main/java/com/adyen/model/checkout/details/UpiCollectDetails.java
- src/main/java/com/adyen/model/checkout/details/UpiIntentDetails.java
- src/test/java/com/adyen/CheckoutTest.java
> [PW-6440] Add UpiCollectDetails and UpiDetails

- pom.xml
Remove the  `jackson.version` variable as the version do not match for all three
- Tests pass
> Update pom file dependencies

- src/main/java/com/adyen/model/checkout/CreatePaymentLinkRequest.java
Added new model and added some changes so UT ran successfully. 
UT
**Fixed issue**:  #784
> #784 Add newer model to CreatePaymentLinkRequest to fix missing themeID parameter 

- src/main/java/com/adyen/model/marketpay/CreateAccountHolderRequest.java
LegalEntityEnum missed some values, so I added the new model and ran the tests.
**Fixed issue**:  #707
> [PW-6494] renewed the CreateAccountHolderRequest model

- src/main/java/com/adyen/deserializer/PaymentMethodDetailsDeserializerJackson.java
- src/main/java/com/adyen/deserializer/PaymentMethodDetailsTypeAdapter.java
- src/main/java/com/adyen/model/checkout/details/GenericIssuerPaymentMethodDetails.java
- src/test/java/com/adyen/CheckoutTest.java
Issuer would disappear from payment requests after serialisation.
Tested by updating the unit tests
> fix paymentmethod serialization for indian banking and wallets

- src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
add ssc to saleToAcquirerData model
> add ssc to saleToAcquirerData model

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
Bump the version to 18.1.0 it was not updated in the release pr 
- #794
> Bump the version to 18.1.0

- README.md
- src/main/java/com/adyen/httpclient/AdyenHttpClient.java
This change allows merchants to configure a few extra HTTP client settings via Java system properties.
* [Java Networking and Proxies](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
* [Available properties](https://hc.apache.org/httpcomponents-client-5.1.x/5.1/httpclient5/apidocs/org/apache/hc/client5/http/impl/classic/HttpClientBuilder.html)
* Checkout API
fixes #811
> PW-7215: Allow client configuration via system properties

- .github/workflows/models.yml
- .openapi-generator-ignore
- Makefile
- pom.xml
Adds a new Github Actions workflow to generate models based on the the latest version of the specs published at [Adyen/adyen-openapi](https://github.com/Adyen/adyen-openapi). Detected changes are proposed via an automatic PR like this https://github.com/Adyen/adyen-java-api-library/pull/810. 
**TODO**
> PW-7045: Model generation workflow

- Makefile
This updates automation so models for Checkout will be generated by the automation flow.
**Fixed issue**:  part of [PW-7050](https://youtrack.is.adyen.com/issue/PW-7050)
> Update MakeFile to generate Checkout Files

- src/main/java/com/adyen/terminal/security/NexoCrypto.java
Based on PR #776 and feedback from our security team.
> Secure PRNG for ivNonce in NexoCrypto based on strongest non blocking instance

- src/main/java/com/adyen/enums/Region.java
> add India to Region Enum

- Makefile
- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
- src/main/java/com/adyen/enums/Region.java
- src/main/java/com/adyen/model/ThreeDSecureData.java
- src/test/java/com/adyen/PaymentTest.java
- templates/libraries/okhttp-gson/AbstractOpenApiSchema.mustache
- templates/libraries/okhttp-gson/JSON.mustache
- templates/libraries/okhttp-gson/oneof_model.mustache
- templates/libraries/okhttp-gson/pojo.mustache
> Release 18.1.3

- README.md
#882 mentioned that link was broken.
> Update Broken Link

- src/main/java/com/adyen/service/Payout.java
Created new storeDetailAndSubmitThirdParty method with RequestOptions parameter to be able to set idempotencyKey.
> Added requestOptions to storeDetailAndSubmitThirdParty in Payout API

- README.md
Update Java Library Readme in preparation of new Major release
> Pw 7465/update docs

- src/main/java/com/adyen/service/Checkout.java
- src/main/java/com/adyen/service/CheckoutUtility.java
add requestoptions for all service calls supporting idempotency keys
> add requestoptions for all service calls supporting idempotency keys

- README.md
`paymentsRequest` should have been `paymentRequest `
> fix typo in payments example

- src/main/java/com/adyen/service/management/AccountCompanyLevel.java
- src/main/java/com/adyen/service/management/AccountMerchantLevel.java
- src/main/java/com/adyen/service/management/AccountStoreLevel.java
- src/main/java/com/adyen/service/management/ApiCredentialsCompanyLevel.java
- src/main/java/com/adyen/service/management/ApiCredentialsMerchantLevel.java
- src/main/java/com/adyen/service/management/PaymentMethodsMerchantLevel.java
- src/main/java/com/adyen/service/management/TerminalActionsCompanyLevel.java
- src/main/java/com/adyen/service/management/TerminalOrdersCompanyLevel.java
- src/main/java/com/adyen/service/management/TerminalOrdersMerchantLevel.java
- src/main/java/com/adyen/service/management/TerminalSettingsCompanyLevel.java
- src/main/java/com/adyen/service/management/TerminalSettingsMerchantLevel.java
- src/main/java/com/adyen/service/management/TerminalSettingsStoreLevel.java
- src/main/java/com/adyen/service/management/TerminalsTerminalLevel.java
- src/main/java/com/adyen/service/management/UsersCompanyLevel.java
- src/main/java/com/adyen/service/management/UsersMerchantLevel.java
- src/main/java/com/adyen/service/management/WebhooksCompanyLevel.java
- src/main/java/com/adyen/service/management/WebhooksMerchantLevel.java
- templates/libraries/okhttp-gson/api.mustache
Fixes Javadoc validation issues.
> PW-8005: Fix Javadoc issues

- src/main/java/com/adyen/service/exception/ApiException.java
- src/main/java/com/adyen/service/resource/Resource.java
- src/test/java/com/adyen/BinLookupTest.java
- src/test/java/com/adyen/ErrorHandlingTest.java
- src/test/java/com/adyen/MarketPayTest.java
- src/test/java/com/adyen/PaymentTest.java
- src/test/java/com/adyen/PayoutTest.java
- src/test/java/com/adyen/PosPaymentTest.java
- src/test/java/com/adyen/RecurringTest.java
- src/test/java/com/adyen/service/ResourceTest.java
This PR removes the deserialization or the custom error and just pass the response in the error message.
Integration Tests (ignored)
> [PW-8014] Removed Error Deserialization

- src/main/java/com/adyen/constants/ApiConstants.java
- src/main/java/com/adyen/httpclient/AdyenHttpClient.java
Sends application info via dedicated headers.
> PW-8051: Application info via headers

- src/main/java/com/adyen/notification/NotificationHandler.java
- src/test/java/com/adyen/NotificationTest.java
- src/test/resources/mocks/notification/display-notification.json
- src/test/resources/mocks/notification/event-notification.json
Notification Handler for terminal notifications.
Also solves #936
> [ITT-76] Created notification handler for Terminal event/display notifications

- README.md
PR to update the snippet of the webhook payload processing in the README.
The array of `NotificationItems` include always a single element, the new snippet shows how to process it and validate the HMAC signature.
> Update HMAC validation snippet

- .github/workflows/publish.yml
- pom.xml
Used the official maven release workflow from github -> https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
> [ITT-26] Automate Maven release

- .github/workflows/publish.yml
Hotfix the publish pipeline as we do need to sign it with gpg.
> Hotfix the publish pipeline

- .github/workflows/publish.yml
the distribution id was not correct..
> Hotfix2-patch-release-workflow

- src/main/java/com/adyen/deserializer/MarketPayNotificationMessageDeserializer.java
- src/main/java/com/adyen/model/marketpay/notification/AccountCloseNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountCreateNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountFundsBelowThresholdNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderCreateNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderPayoutNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderStatusChangeNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderStoreStatusChangeNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderUpcomingDeadlineNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderUpdateNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountHolderVerificationNotification.java
- src/main/java/com/adyen/model/marketpay/notification/AccountUpdateNotification.java
- src/main/java/com/adyen/model/marketpay/notification/BeneficiarySetupNotification.java
- src/main/java/com/adyen/model/marketpay/notification/CompensateNegativeBalanceNotification.java
- src/main/java/com/adyen/model/marketpay/notification/DirectDebitInitiatedNotification.java
- src/main/java/com/adyen/model/marketpay/notification/GenericWebhook.java
- src/main/java/com/adyen/model/marketpay/notification/PaymentFailureNotification.java
- src/main/java/com/adyen/model/marketpay/notification/RefundFundsTransferNotification.java
- src/main/java/com/adyen/model/marketpay/notification/ReportAvailableNotification.java
- src/main/java/com/adyen/model/marketpay/notification/ScheduledRefundsNotification.java
- src/main/java/com/adyen/model/marketpay/notification/TransferFundsNotification.java
- src/main/java/com/adyen/notification/WebhookHandler.java
- src/test/java/com/adyen/MarketPayNotificationTest.java
- src/test/java/com/adyen/WebhookTest.java
Rename notifications to Webhook for the classes that are not autogenerated 
All tests are passing
> [ITT-446] Rename notifications to Webhook

- Makefile
Fixes the pipeline error: https://github.com/Adyen/adyen-java-api-library/actions/runs/5065596672/jobs/9094351392#step:3:38
> Fix shell redirect error

- README.md
- pom.xml
- src/main/java/com/adyen/Client.java
Bump library version to 20.1.0
> Release 20.1.0

- src/main/java/com/adyen/model/notification/NotificationRequest.java
- src/main/java/com/adyen/model/notification/NotificationRequestItemContainer.java
- src/main/java/com/adyen/notification/WebhookHandler.java
- src/test/java/com/adyen/WebhookTest.java
Quick fix to support jackson in the old webhook model.
> Jackson support webhooks

- src/test/java/com/adyen/LegalEntityManagementTest.java
- src/test/java/com/adyen/PaymentTest.java
- src/test/java/com/adyen/TransfersTest.java
Fix unit tests for automation models and services
All tests pass
> Fix tests automation/services

- Makefile
> Bump versions

- README.md
- src/test/java/com/adyen/MarketPayTest.java
- src/test/java/com/adyen/service/ResourceTest.java
- src/test/resources/mocks/afp-validation-error.json
- src/test/resources/mocks/invalid-phone-afp-response.json
Adds new tests for error handling of Classic AFP responses.
> Test error handling for Classic AFP

- README.md
adds a deserialization section to  the readme
> add deserialization guide to readme

- templates/libraries/jersey3/pojo.mustache
> Remove default values from lib

- README.md
Usage of content in Attachments was unclear.
Updated readme gives brief clarification about the usage
> updated readme for Document API

- src/main/java/com/adyen/model/notification/NotificationRequestItem.java
Added pspReference it is required for recurring contract
**Fixed issue**:  1298
> add psp reference

- src/main/java/com/adyen/Service.java
added returns so createBaseUrl returns test if environment is not live or returns live if environment is not test
> added return for live and test prefix

- src/main/java/com/adyen/terminal/security/NexoCrypto.java
This PR improves the process of encryption and decryption for local terminal testing by using dynamically-generated, random IV.
> Use a dynamically-generated, random IV

- pom.xml
PR to update the Java version in the `pom.xml`, aligned with minimum version supported (as stated on README)
> Update Java version in POM file

- .gitignore
- src/main/java/com/adyen/util/HMACValidator.java
- src/test/java/com/adyen/util/HMACValidatorTest.java
- tools/hmac/CalculateHmacPayments.java
- tools/hmac/CalculateHmacPlatform.java
- tools/hmac/README.md
- tools/hmac/payload.json
- tools/hmac/payload2.json
- tools/hmac/pom.xml
Add a small Maven project in `tools/hmac` to troubleshoot the HMAC signature computation of the Java library
> HMAC Troubleshooting tool

- src/main/java/com/adyen/Config.java
- src/main/java/com/adyen/httpclient/AdyenHttpClient.java
Set default timeouts (to 60 sec) for the Http Connection Handler.
> HTTP Client timeouts

- src/main/java/com/adyen/service/PaymentApi.java
- src/main/java/com/adyen/service/PosTerminalManagementApi.java
Deprecate legacy code that should no longer be used
> Deprecate legacy code [PosTerminalManagementApi, PaymentApi]

- README.md
Minor edit in README (webhook parsing)
> FIX: Correct README

- src/main/java/com/adyen/ApiKeyAuthenticatedService.java
- src/main/java/com/adyen/Service.java
- src/main/java/com/adyen/builders/terminal/TerminalAPIRequestBuilder.java
- src/main/java/com/adyen/httpclient/AdyenHttpClient.java
- src/main/java/com/adyen/httpclient/TerminalLocalAPIHostnameVerifier.java
- src/main/java/com/adyen/util/CertificateUtil.java
- src/main/java/com/adyen/util/DateUtil.java
- src/main/java/com/adyen/util/HMACValidator.java
- src/main/java/com/adyen/util/MaskUtil.java
- src/main/java/com/adyen/util/Util.java
> Improve Javadoc in several classes

- src/test/java/com/adyen/BalancePlatformWebhooksTest.java
- src/test/resources/mocks/balancePlatform-webhooks/transfer-updated.json
Add unit test for TransferNotificationRequest webhook
> TransferWehooks: add test

- src/main/java/com/adyen/model/nexo/EventToNotifyType.java
Add new Event Type `ScanBarcodeResult`
> Add ScanBarcodeResult event type

- src/test/java/com/adyen/CheckoutTest.java
> Add test with idempotency key

- src/main/java/com/adyen/Service.java
PR to improve the custom handling of POS Mobile API url: the endpoint path is enough to trigger the url manipulation, no need to check the API version. 
This aligns with the solution implemented in the Python library.
> Improve POSSDK live endpoint construction
