pom.xml
src/main/java/com/adyen/Util/HMACValidator.java
src/test/java/com/adyen/BaseTest.java

Hi, I found that guava is used only to encode/decode data and appears only in one place (see changes in HMACValidator.java). This code can be easily replaced by methods from commons-codec which is also on classpath.
In addition I removed dependency to commons-io because reading stream to String can be done efficiently in plain Java (see changes in BaseTest.java). 
Last thing in this pull request is test scope for mockito-core.
All this changes reduced size of generated jar file from 6.5MB to 1.1MB, functionality remains unchanged.

Removed guava and commons-io, introduced test scope for mockito-core

---

src/main/java/com/adyen/model/recurring/RecurringDetailsResult.java
src/test/java/com/adyen/RecurringTest.java

Added invalidOneclickContracts into the RecurringDetailResult model to allow this field to be parsed from the JSON result to the model.
Add the field into the test to verify if it worked
#76

#76 Add missing field invalidOneclickContracts

---

src/main/java/com/adyen/service/Payment.java

The generic exception was changed to a specific exception called ApiException. This change was necessary because the generic exception return was hiding the returned error values.
Without this correction the exception of  authorise was returning just a com.adyen.service.exception.ApiException: HTTP Exception.

Correction on return of exception (method authorise of Payment). 

---

README.md
src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java

Add proxy configuration in HttpURLConnectionClient so that the client library can be used when behind an HTTP or Socks proxy
HTTP proxy

Add proxy configuration in HttpURLConnectionClient

---

README.md
docs/install-library.html
pom.xml
src/main/java/com/adyen/Client.java
src/main/java/com/adyen/model/marketpay/CreateAccountHolderResponse.java
src/main/java/com/adyen/model/marketpay/GetAccountHolderResponse.java
src/test/java/com/adyen/MarketPayTest.java

Updated MarketPay CreateAccountHolderResponse, GetAccountHolderResponse including correction of verification results in getAccountHolder

Updated MarketPay CreateAccountHolderResponse, GetAccountHolderResponse

---

src/main/java/com/adyen/Util/DateUtil.java
src/main/java/com/adyen/constants/ApiConstants.java
src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
src/main/java/com/adyen/model/PaymentResult.java
src/main/java/com/adyen/model/checkout/PaymentsRequest.java
src/main/java/com/adyen/model/checkout/PaymentsResponse.java

Use API key if provided
Added PaymentsRequest constants and helpers
Payments and Modifications

Use API key if provided

---

src/main/java/com/adyen/model/modification/CaptureRequest.java
src/main/java/com/adyen/model/modification/RefundRequest.java
src/test/java/com/adyen/BaseTest.java
src/test/java/com/adyen/ModificationTest.java

In `RefundRequest` and `CaptureRequest` all chaining methods returns `RefundRequest` and `CaptureRequest` respectively except for `modificationAmount` (it returns `AbstractModificationRequest` in both classes).
This is a follow up to [this PR](https://github.com/Adyen/adyen-java-api-library/pull/114). As @lancergr requested, applied the changes to `CaptureRequest` too.

Make modificationAmount() return RefundRequest and CaptureRequest

---

src/main/java/com/adyen/model/checkout/PaymentsResponse.java
src/main/java/com/adyen/model/checkout/ServiceError.java

Add payments/details missing attributes  (authResult, serviceError and merchantReference)  to PaymentsResponse

Add payments/details missing attributes to PaymentsResponse

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/constants/ApiConstants.java
src/main/java/com/adyen/model/checkout/PaymentsRequest.java
src/test/java/com/adyen/CheckoutTest.java

Add helper to easily provide card data as well added a new constructor to set required fields for better sample code and easier integration.

Add helper to set raw card data

---

docs/install-library.html
docs/using-library.html

…1.5.4
(cherry picked from commit 271e6b1)

[PW-689]: doc change only** setEnvironment instructions and library version update

---

src/main/java/com/adyen/model/recurring/StoreTokenRequest.java
src/main/java/com/adyen/model/recurring/StoreTokenResult.java
src/main/java/com/adyen/service/Recurring.java
src/main/java/com/adyen/service/resource/recurring/StoreToken.java
src/test/java/com/adyen/RecurringTest.java
src/test/resources/mocks/recurring/storeToken-error-101.json
src/test/resources/mocks/recurring/storeToken-success.json

**Description** 
/recurring/storeToken API implementation is missing in adyen java lib. Adding an implementation similar to other /recurring APIs.

Add StoreToken API implementation

---

docs/checkout-api.html
docs/checkout-sdk.html

added idempotency key instructions.

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java

See Adyen Support ticket #447790
Tested locally simulating network outage after establishing initial connection.

Custom read timeout for HttpURLConnection

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
src/main/java/com/adyen/model/PaymentRequest.java
src/main/java/com/adyen/model/PaymentResult.java
src/main/java/com/adyen/model/applicationinfo/ApplicationInfo.java
src/main/java/com/adyen/model/applicationinfo/CommonField.java
src/main/java/com/adyen/model/applicationinfo/ExternalPlatform.java
src/main/java/com/adyen/model/applicationinfo/MerchantDevice.java
src/main/java/com/adyen/model/applicationinfo/ShopperInteractionDevice.java
src/main/java/com/adyen/model/checkout/PaymentsRequest.java
src/main/java/com/adyen/model/modification/AbstractModificationRequest.java
src/test/java/com/adyen/BaseTest.java
src/test/java/com/adyen/CheckoutTest.java
src/test/java/com/adyen/PaymentRequestBuilderTest.java

Route checkout api calls to v40 (additional fields are not included)
Added application info
payments including application info

Route checkout api calls to v40 and added application info

---

src/main/java/com/adyen/model/marketpay/GetAccountHolderRequest.java

As described in Issue #146 the GetAccountHolder is missing the parameter showDetails
Requesting GetAccountHolder with and without showDetails
**Fixed issue**:  #146

fixes Issue #146 Adding showDetails to getAccountHolder

---

pom.xml

Removed log4j dependency
log4j is not used. It compiles without it.
**Fixed issue**:  #159

[REMOVE-LOG-DEP]: Remove log4j dependency

---

src/main/java/com/adyen/model/checkout/PaymentResultResponse.java

Based on the [api documentation](https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v41/payments/result) partially authorized result code is not used. Further more Pending result code is added 
closes #181

Add pending status

---

src/main/java/com/adyen/model/checkout/PaymentsResponse.java
src/test/java/com/adyen/CheckoutTest.java

Multibanco amount null check before cast to BigDecimal
Empty multibanco amount returns null and not throw exception

BugFix Multibanco Null check added

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/model/binlookup/CardBin.java
src/main/java/com/adyen/model/binlookup/CostEstimateAssumptions.java
src/main/java/com/adyen/model/binlookup/CostEstimateRequest.java
src/main/java/com/adyen/model/binlookup/CostEstimateResponse.java
src/main/java/com/adyen/model/binlookup/DSPublicKeyDetail.java
src/main/java/com/adyen/model/binlookup/MerchantDetails.java
src/main/java/com/adyen/model/binlookup/Recurring.java
src/main/java/com/adyen/model/binlookup/ThreeDS2CardRangeDetail.java
src/main/java/com/adyen/model/binlookup/ThreeDSAvailabilityRequest.java
src/main/java/com/adyen/model/binlookup/ThreeDSAvailabilityResponse.java
src/main/java/com/adyen/serializer/ByteArrayToBase64TypeAdapter.java
src/main/java/com/adyen/service/BinLookup.java
src/main/java/com/adyen/service/resource/binlookup/Get3dsAvailability.java
src/main/java/com/adyen/service/resource/binlookup/GetCostEstimate.java
src/test/java/com/adyen/BinLookupTest.java
src/test/resources/mocks/binlookup/get3dsavailability-error-merchant.json
src/test/resources/mocks/binlookup/get3dsavailability-success.json
src/test/resources/mocks/binlookup/getcostestimate-error-amount.json
src/test/resources/mocks/binlookup/getcostestimate-error-cardnumber.json
src/test/resources/mocks/binlookup/getcostestimate-error-merchant.json
src/test/resources/mocks/binlookup/getcostestimate-success.json

Added BinLookup API /getCostEstimate and /get3dsAvailability
Success and fail cases with different request data

added models, services and mocking test for binlookup apis

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/Config.java
src/main/java/com/adyen/Util/Util.java
src/main/java/com/adyen/model/Amount.java
src/main/java/com/adyen/model/marketpay/AccountHolderDetails.java
src/test/java/com/adyen/MarketPayTest.java
src/test/java/com/adyen/UtilTest.java

While investigated and debugged the library I found some small performance issues.
Also I was lack of some documentation so I added it to JavaDoc

Small optimizations and cleanup

---

src/main/java/com/adyen/model/ThreeDSecureData.java
src/main/java/com/adyen/model/checkout/ThreeDSecureData.java

Missing value according to docs and core code
```
"directoryResponse" : {
"description" : "In 3D Secure 1, this is the enrollment response from the 3D directory server.\n\nIn 3D Secure 2, this is the `transStatus` from 3D Secure device fingerprinting result.",
"enum" : [
"Y",
"N",
"U",
"E",
"C"
],
"type" : "string"
},
```

Add missing value to DirectoryResponseEnum

---

pom.xml
src/main/java/com/adyen/model/PaymentResult.java
src/test/java/com/adyen/PaymentResultTest.java

Unable to retrieve result code `AuthenticationFinished` from API response
Without change, test provided fails. With change, test passes
**Fixed issue**: #197

Add `AuthenticationFinished` resultCode to `ResultCodeEnum`

---

src/main/java/com/adyen/service/Payment.java

`authorise3D` method in `Payment.java` which is used by library consumers is throwing `Exception`, instead of throwing `ApiException`, `IOException`.  Hence consumers are forced to handle this generic exception.
As this is a small refactoring, no tests were needed.
This is not an issue, and just a small refactoring.

Throw specific exception instead of a generic one

---

src/main/java/com/adyen/model/PaymentRequest.java

The calls for the super methods where removed by mistake on a previous commit.
Reverting this changes on the `toString`, `hash` and `equals` methods.
**Fixed issue**:  #247

Fix PaymentRequest methods

---

src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java

Renamed "idealIssuer" to "issuer" on DefaultPaymentMethodDetails

---

src/main/java/com/adyen/service/Resource.java
src/main/java/com/adyen/service/exception/ApiException.java

This story is about to access the Transient-Error header value through http client exception. The response returns an HTTP 409 – Conflict status with the error code 704: "request already processed or in progress" but not any http headers.
For information about the Transient-Error check [docs](https://docs.adyen.com/development-resources/api-idempotency#transient-errors)
Internal e2e test /payments making two transactions with the same idempotency key.
**Fixed issue**:   #284

[PW-2034] Add http response headers to ApiException

---

src/main/java/com/adyen/model/checkout/DefaultPaymentMethodDetails.java
src/test/java/com/adyen/CheckoutTest.java

Field replaces _recurringDetailReference_

[PW-2114] Added "storedPaymentMethodId" to DefaultPaymentMethodDetails

---

src/main/java/com/adyen/model/nexo/BarcodeType.java
src/main/java/com/adyen/model/nexo/OutputBarcode.java

This PR addresses two issues:
- Changing the BarcodeType-ENUM from `QRCODE` to `QRCode`
- Changing the barcode's value to `barcodeValue`
None, since the only terminal available to me, the V400m, apparently doesn't support `DisplayRequest` calls.
However, these fixes take the error messages from "Unexpected field value" and "field barcodeValue missing" to "Unsupported output format" - which seems like an improvement?
**Fixed issue**:  No issue opened

Update BarcodeOuput to reflect API doc

---

src/main/java/com/adyen/model/checkout/ThreeDS2Result.java
src/test/java/com/adyen/CheckoutTest.java
src/test/resources/mocks/checkout/payments-3ds2-authentication-finished.json

com.adyen.model.checkout.ThreeDS2Result has field messageVersion missing. Field has been available since at least July. We had been processing it already since then.
N/A
Issue has not been logged (as far as I know)

Added missing messageVersion field to ThreeDS2Result

---

src/main/java/com/adyen/model/notification/NotificationRequestItem.java
src/test/java/com/adyen/NotificationTest.java
src/test/resources/mocks/notification/cancellation-true.json
src/test/resources/mocks/notification/chargeback.json

- Creating constantes for all notification codes, got it from https://docs.adyen.com/development-resources/notifications/understand-notifications#event-codes
- Dedup of test code at NotificationTest class
Parser of cancellation and chargeback events
https://github.com/Adyen/adyen-java-api-library/issues/307
**Question**
Do really make sense create tests for every event code? Looking at `NotificationRequestItem.class`, sounds like you are just testing GSON and the contract of the event.
If it's important to test every case, could you guys provide JSON examples? It is hard to find examples for every event at the site.

Including all notification codes as constants

---

src/main/java/com/adyen/model/modification/ModificationResult.java
src/main/java/com/adyen/model/modification/TechnicalCancelRequest.java

This fixes a couple small issues with the technical-cancel API.
After vendoring this change into our application, I successfully sent a technical-cancel request and saw the expected response code in the API response.

Technical cancel api fix

---

src/test/java/com/adyen/CheckoutTest.java
src/test/resources/mocks/checkout/payments-encrypted-success.json

Added tests with encrypted card details that don't need a component to be encrypted(only works on test),
for more examples see:
https://docs.adyen.com/checkout/api-only?tab=%23codeBlockitIb5_Java#step-3-make-a-payment
and the API explorer scenarios:
https://docs.adyen.com/api-explorer/#/PaymentSetupAndVerificationService/v52/payments__example_payments-card-securedfields

PW-2192: Added tests with encrypted card details

---

src/main/java/com/adyen/service/Payout.java

add idempotency key for instant payouts with requestoptions

PW-2506: add idempotency key for instant payouts

---

src/main/java/com/adyen/model/modification/ModificationResult.java
src/test/java/com/adyen/ModificationTest.java

some Modifications operations can result in synchronous responses, which are not included in the actual ResponseEnum.
Reason for this pull request is to allow all possible responses by changing the type of the variable to String.
This is a breaking change since the 'response' field type of these operations changed:
/adjustAuthorisation
/cancel
/cancelOrRefund
/capture
/donate
/refund
/technicalCancel
/voidPendingRefund
the ResponseEnum field is still there with a deprecated tag and message.

PW-2623: change the 'response' field type of ModificationResult to String

---

src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java

JKS keystore is not available on Android. This fix uses the default keystore.
I have only tested on Android
**Fixed issue**:  #383

fix: Android - java.security.KeyStoreException: JKS not found

---

src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java

Currently the only way to provide a terminal certificate to the library is via Config.terminalCertificatePath. On Android it makes more sense to store the certificates as resources as opposed to files in the file system.
Tested on Android only
**Fixed issue**:  #388

feat(config): terminal certificate stream

---

src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java

InputStream can only be reset if the given stream supports mark and it is set to correct position, otherwise it will throw IOException. Hence we have to assume that the stream is at the start of certificate data.
**Fixed issue**:  #402

PW-2994 InputStream can only be reset if mark is supported

---

src/main/java/com/adyen/model/checkout/ThreeDSecureData.java
src/test/java/com/adyen/service/CheckoutTest.java

Changed the type of xid and cavv from byte[] to String, as they are returned as String already from https://docs.adyen.com/api-explorer/#/Payment/v64/post/getAuthenticationResult

PW-3158: change type from byte[] to String in ThreeDSecureData

---

src/main/java/com/adyen/model/modification/ModificationResult.java
src/test/java/com/adyen/ModificationTest.java

Added constants for the field `response` in the `ModificationResult` class. 
All tests for `ModificationResult` model. 
#458

PW-3434 Added response constant for ModificationResult response field.

---

src/main/java/com/adyen/terminal/security/NexoCrypto.java

All terminals are working in UTF_8, might be a breaking change, will release major version.
Local terminal test display QR code with text and UTF_8 characters

PW-3870: Encrypt method change from ASCII to UTF_8

---

src/main/java/com/adyen/model/checkout/PaymentsRequest.java
src/test/java/com/adyen/CheckoutTest.java
src/test/resources/mocks/checkout/payments-encrypted-without-holdername-success.json

Overload _addEncryptedCardData_ so it can be used without _holdername_.

Overload addEncryptedCardData method to use without holdername

---

src/main/java/com/adyen/model/marketpay/notification/AccountCreatedNotification.java
src/test/java/com/adyen/MarketPayNotificationTest.java
src/test/resources/mocks/marketpay/notification/account-created-success.json

The notification AccountCreatedNotification contains the wrong content type (CreateAccountHolderResponse instead of CreateAccountResponse) and therefore some fields from the notification are not available.

Change AccountCreated notification content

---

src/main/java/com/adyen/model/DeviceRenderOptions.java

According to specs: https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments__reqParam_threeDS2RequestData-deviceRenderOptions-sdkInterface the the first letter of the values of `sdkInterface` is lowercase.
**Fixed issue**:  #510

fix sdkInterfaceEnum for the values html and native. Fixes #510

---

src/main/java/com/adyen/model/marketpay/KYCCheckStatusData.java
src/test/java/com/adyen/MarketPayNotificationTest.java
src/test/java/com/adyen/MarketPayTest.java

added missing enum values to KYCCheckStatusData.
getters/setters for these fields in KYCCheckStatusData changed:
`checkStatus` -> `status`
`checkType` -> `type`
major version bump is needed.

Added missing enum values to KYCCheckStatusData, updated tests

---

src/main/java/com/adyen/terminal/security/TerminalCommonNameValidator.java

Using the matcher.group() function with the parameter of int instead of String. Stops an 'UnsupportedOperationException' being thrown when used on some Android devices.
- group(1) returns the common name
- group(2) returns the value
It seems like the internals of the matcher.group(String) function works out the index before executing the same code as the matcher.group(index). 
Also, checked to make sure that matcher.group(int) was not deprecated before using it, still a supported and used method.
- Tested changes on Android devices with the OS ranging from 7-10
- Executed the existing test scripts in the TerminalCommonNameValidatorTest class 

Changed matcher.group() parameter to prevent UnsupportedOperationException on some older Android devices.

---

src/main/java/com/adyen/model/marketpay/notification/AccountHolderPayoutNotificationContent.java
src/test/java/com/adyen/MarketPayNotificationTest.java
src/test/resources/mocks/marketpay/notification/account-holder-payout.json

Changing the type of the estimatedArrivalDate field on the AccountHolderPayoutNotificationContent from LocalDate to Date because parsing to LocalDate did lead to an exception.
**Fixed issue**:  #539

Parsing ACCOUNT_HOLDER_PAYOUT notification throws exception

---

src/main/java/com/adyen/terminal/security/TerminalCommonNameValidator.java

Even older Android devices (SDK22) still crash at regex pattern compilation with Syntax error in regexp pattern near index 17: (?:^|,\s?)(?:(?<name>[A-Z]+)=(?<val>"(?:[^"]|"")+"|[^,]+))+
It's just an addition to tshakesp's commit 775e2bb0aca4e6465e2266c3539cae5e1202813d removing named groups in the regex.

Remove named groups from the regex

---

src/main/java/com/adyen/model/nexo/Amount.java
src/test/java/com/adyen/TerminalCloudAPITest.java
src/test/resources/mocks/terminal-api/payment-sync-success.json

current structure according to: https://docs.adyen.com/point-of-sale/terminal-api-reference#comadyennexoconvertedamount
**Fixed issue**: ConvertedAmount could not be deserialized correctly(amountValue was missing)

fix: change `value` to `amountValue` in adyen.model.nexo.amount

---

src/main/java/com/adyen/model/nexo/StoredValueResponse.java
src/test/java/com/adyen/TerminalCloudAPITest.java
src/test/resources/mocks/terminal-api/payment-sync-success-storedvalue.json

adding paymentReceipt in storedValueResponse as explained here https://docs.adyen.com/point-of-sale/terminal-api-reference#comadyennexostoredvalueresponse

fix: add `paymentReceipt` to StoredValueResponse

---

src/main/java/com/adyen/httpclient/AdyenHttpClient.java

The Apache Http client uses the ISO-8859-1 encoding for request bodies. This is not compatible with the rest endpoint and the encoding declared in the header of the request (UTF-8).
**Fixed issue**:  #565

HTTP Client wrong encoding

---

src/main/java/com/adyen/httpclient/AdyenHttpClient.java

Android throws `java.security.KeyStoreException: JKS not found` as it (the Dalvik virtual machine) does not provide JKS key store type. Please, see KeyStore description at https://developer.android.com/reference/java/security/KeyStore
The call to KeyStore.getDefaultType() was used in HttpURLConnectionClient.java until the refactor to AdyenHttpClient.java in 15.0.0 where it was replaced with the JAVA_KEYSTORE constant. Please, keep using KeyStore.getDefaultType().
**See:**
https://github.com/Adyen/adyen-java-api-library/blob/14.0.0/src/main/java/com/adyen/httpclient/HttpURLConnectionClient.java
https://github.com/Adyen/adyen-java-api-library/blob/15.0.0/src/main/java/com/adyen/httpclient/AdyenHttpClient.java

Use KeyStore.getDefaultType()

---

src/main/java/com/adyen/httpclient/AdyenHttpClient.java

Handle `null` for `requestBody`. 
hpp passes null as requestBody for 'directoryLookup'
Get payment methods via hpp
#552

PW-4719 Handle null for requestBody

---

src/main/java/com/adyen/terminal/security/TerminalCommonNameValidator.java
src/test/java/com/adyen/terminal/security/TerminalCommonNameValidatorTest.java

TerminalCommonNameValidator does not support certificates from Castles terminals. Updated the logic in the following way:
- Minimum length of terminal model name has been changed from 4 to 3 characters (to account for `S1E`)
- Changed regular expression for serial number to allow a range from 9 to 15 digits (to account for all Castles serial numbers)
- Added a `null` check for return value from `Matcher.group(int)`
Added tests for `S1E` CN.
**Fixed issue**:  Partially FOC-47780

FOC-47780: Update TerminalCommonNameValidator to support validation of Castles certificates

---

src/main/java/com/adyen/model/marketpay/BusinessDetails.java
src/main/java/com/adyen/model/marketpay/FieldType.java
src/main/java/com/adyen/model/marketpay/KYCUltimateParentCompanyCheckResult.java
src/main/java/com/adyen/model/marketpay/KYCVerificationResult.java
src/main/java/com/adyen/model/marketpay/UltimateParentCompany.java
src/main/java/com/adyen/model/marketpay/UltimateParentCompanyBusinessDetails.java
src/test/java/com/adyen/MarketPayTest.java
src/test/resources/mocks/marketpay/account/get-business-account-holder-with-parent-success.json

Used to supply parent company information.
Add the missing `listedUltimateParentCompany` field, see also https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder__reqParam_accountHolderDetails-businessDetails-listedUltimateParentCompany.
Also add it in the KYC verification result (https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder__resParam_verification-ultimateParentCompany).
- Manual request with populated `listedUltimateParentCompany`, and verified that it arrives correctly at Adyen (and that the response can be parsed).
- JUnit test for checking that the JSON is parsed correctly into the model.
**Fixed issue**: N/A.

Add support for UltimateParentCompany

---

src/main/java/com/adyen/model/nexo/PaymentInstrumentData.java

ContentInformation is not parsed yet at the terminal side. As an intermediate solution ProtectedCardData will be changed to type string so that it may be parsed by the terminal
**Fixed issue**:  #666

change ProtectedCardData type from ContentInformation to String

---

src/main/java/com/adyen/model/checkout/PaymentMethodsRequest.java

When using the PaymentMethodsRequest and sending a request with apiVersion 67 one will receive a validation error:
'Structure of PaymentMethodsRequest contains the following unknown fields: [enableRealTimeUpdate]'
This field was deprecated but not removed in PaymentMethodsRequest bean.
fixes: #622

Remove enableRealTimeUpdate

---

src/main/java/com/adyen/util/HMACValidator.java
src/test/java/com/adyen/util/HMACValidatorTest.java

Hmac validator is not null safe, because notificationRequestItem.getAdditionalData().get(HMAC_SIGNATURE) returns null if addtionalData does not contain a key "hmacSignature" (or a possible null value for key "hmacSignature").
There is an extra null-safe check implented in this PR
Fixes #623

Hmac validator null-safe check

---

src/main/java/com/adyen/model/marketpay/notification/PaymentFailureNotificationContent.java

added missing Fields for PaymentFailureNotificationContent.modificationMerchantReference, .modificationPspReference, .paymentMerchantReference, .paymentPspReference
**Fixed issue**:  #603

Added missing Fields for PaymentFailureNotificationContent

---

.github/CODEOWNERS
.github/workflows/codeql-analysis.yml
.github/workflows/coveralls.yml
.github/workflows/javaci.yml
README.md
pom.xml
src/main/java/com/adyen/Client.java
src/main/java/com/adyen/deserializer/PaymentMethodDetailsDeserializerJackson.java
src/main/java/com/adyen/deserializer/PaymentMethodDetailsTypeAdapter.java
src/main/java/com/adyen/model/ThreeDS2RequestData.java
src/main/java/com/adyen/model/checkout/details/PayWithGoogleDetails.java
src/main/java/com/adyen/model/checkout/details/UpiCollectDetails.java
src/main/java/com/adyen/model/checkout/details/UpiIntentDetails.java
src/main/java/com/adyen/model/marketpay/notification/PaymentFailureNotificationContent.java
src/main/java/com/adyen/model/nexo/Input.java
src/main/java/com/adyen/util/HMACValidator.java
src/test/java/com/adyen/CheckoutTest.java
src/test/java/com/adyen/NotificationTest.java
src/test/java/com/adyen/PaymentRequestBuilderTest.java
src/test/java/com/adyen/serializer/SaleToAcquirerDataSerializerTest.java
src/test/java/com/adyen/service/CheckoutTest.java
src/test/java/com/adyen/util/HMACValidatorTest.java

- #697 
- #681 
- #706 
- #731
- #733

Release 17.4.0

---

src/main/java/com/adyen/model/marketpay/CreateAccountHolderRequest.java

According to https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder__reqParam_legalEntity there is NonProfit option missing in current enum implementation for CreateAccountHolder request.

Missing NonProfit CreateAccountHolderRequest.LegalEntityEnum option

---

src/main/java/com/adyen/model/AbstractPaymentRequest.java
src/test/java/com/adyen/PaymentTest.java

Needed to add a setter in AbstractPaymentRequest which extends the PaymentRequest/PaymentRequest3D class. 
Unit Test.
**Fixed issue**:  PW-7093 (issue from partner ChargeBee)

[PW-7093] authorise/authorise3D can set ApplicationInfo

---

src/main/java/com/adyen/model/nexo/AuthenticationMethodType.java

https://docs.adyen.com/point-of-sale/terminal-api-reference#comadyennexoauthenticationmethod
Docs state that OnlinePIN in nexo.authenticationMethod should indeed without L just like the merchant mentioned he received in his respons. Correctly changing XMLEnumValue should not impact current merchant implementations.
**Fixed issue**:  #758

OnLinePIN should be without capital L

---

src/main/java/com/adyen/model/marketpay/ErrorFieldTypeContainer.java
src/main/java/com/adyen/model/marketpay/Message.java
src/main/java/com/adyen/model/marketpay/notification/PaymentFailureNotificationContent.java
src/test/java/com/adyen/model/marketpay/notification/PaymentFailureNotificationTest.java

- Added a default no-args constructor to `ErrorFieldTypeContainer`.
- Added equals and hashCode methods to `Message` and `PaymentFailureNotificationContent`.
I am a developer who integrates Adyen notification webhooks to our Spring application. We are having issues with the `PAYMENT_FAILURE` notification type.
Our Spring framework cannot deserialize the `PaymentFailureNotification` object received from Adyen. `PaymentFailureNotification.PaymentFailureNotificationContent.ErrorFieldTypeContainer` class doesn't have a default no-args constructor required by Jackson (utilized by Spring) to deserialize objects.
Jackson can deserialize `PaymentFailureNotification`.
---
Stacktrace:
```
org.springframework.http.converter.HttpMessageConversionException: Type …
```

Add no-args constructor to ErrorFieldTypeContainer so that it can be deserialized

---

src/main/java/com/adyen/model/PaymentResult.java
src/test/java/com/adyen/PaymentResultTest.java

The result code [AuthenticationNotRequired](https://docs.adyen.com/api-explorer-beta/Payment/52/post/authorise#responses-200-resultCode) was missing from the library. It's already documented and will be added to the specs soon.

PW-7204: Add AuthenticationNotRequired

---

Makefile
pom.xml
templates/libraries/okhttp-gson/AbstractOpenApiSchema.mustache
templates/libraries/okhttp-gson/JSON.mustache
templates/libraries/okhttp-gson/oneof_model.mustache
templates/libraries/okhttp-gson/pojo.mustache

Update templates so they are properly able to parse oneOf models based on allowed Enum Values
Tested using Checkout models and unit tests

Pw 7050/update templates

---

src/main/java/com/adyen/model/ThreeDSecureData.java
src/test/java/com/adyen/PaymentTest.java

Currently, fields of type `byte[]` are serialized as `Number[]`, e.g. `"cavv":[65,81,73,68,66,65,85]`. The API expects a `String`, e.g. `"cavv": "3q2+78r+ur7erb7vyv66vv////8="`.
This PR fixes fields such as [cavv](https://docs.adyen.com/api-explorer/Payment/52/post/authorise#request-mpiData-cavv) used in Classic integrations (i.e. `/authorise` calls). 
**Resources**
* [Authorise a payment with 3D Secure 2 authenticated data](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/other-3ds-flows/authorize-mpidata#send-a-payment-authorisation-request) 
* [Authentication-only integration ](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/3d-secure-1/3d-secure-1-authentication-only#-authoris …

PW-7327: Serialise ByteArray into JSON String

---

src/test/java/com/adyen/DateSerializationTest.java

This quickly fixes the DateSerializerTests as they were failing because Java Calendar sets hours with 12 hour step instead of 24 hours. 

[PW-7223] Test Failed because hours are set with 12 hour instead of 24

---

.github/release.yml

This PR will add the release.yml file to automatically categorize PRs in the release notes, based on the linked labels.

Add release.yml file to automatically categorize PRs

---

src/main/java/com/adyen/model/marketpay/notification/AccountHolderVerificationNotificationContent.java
src/test/java/com/adyen/MarketPayNotificationTest.java
src/test/resources/mocks/marketpay/notification/account-holder-verification.json

Add missing fields, specially `signatoryCode`, from AFP notification model on v18.

PW-6983: Add missing fields from AccountHolderVerificationNotificationContent

---

.github/CODEOWNERS

Adding Jilling and Antoni to codeowners so their contributions and reviews 'count'.

Add nextgen powerhouses to codeOwners

---

src/main/java/com/adyen/Client.java
src/main/java/com/adyen/Config.java
src/test/java/com/adyen/ClientTest.java

This PR fixes the problem we found with initialising the Client with an config object. In order to make it make sense, I added a getter/setter for the liveEndpointUrlPrefix like we did in the .NET library. This way we keep our current implementation of the client but also support the config constructor.
UT

Fixing the constructor with config object in Client.java

---

src/main/java/com/adyen/service/Checkout.java

The generation of Checkout-v70 has introduced the `<br >` element in the javadoc.
This PR removed those elements. The corresponding Mustache template should be updated to make sure it won't happen again during the new code generation.
n/a

Remove <br /> from Javadoc (Checkout)

---

src/main/java/com/adyen/model/notification/NotificationRequest.java
src/main/java/com/adyen/notification/NotificationHandler.java
src/test/java/com/adyen/NotificationTest.java

This fixes the issue our Java-spring example project has with release v19.0.0.
added unit tests to test the setter.
Tested the fix by deploying this fix locally and running the example project on localhost

add setter for notificationItems

---

src/main/java/com/adyen/model/ApiError.java
src/main/java/com/adyen/service/resource/Resource.java
src/test/java/com/adyen/service/ResourceTest.java
src/test/resources/mocks/response-validation-error-rfc7807.json
src/test/resources/mocks/response-validation-error.json

When the API returns an error the `ApiException`does not provide/map the ApiError object
```
} catch (ApiException e) {
log.error(e.getMessage()); // HTTP Exception
log.error(e.getResponseBody());  // {"status":422,"errorCode":"803","message":.....
log.error(e.getError()); // null
```
This PR implements a GSON adapter to map the JSON error to the ApiError object, supporting both format `RFC7807` (returned by LEM and platform APIs) and `ServiceError` legacy format (Checkout)
Added 2 unit tests in `ResourceTest` class
Tested with Adyen Java sample application

ApiException doesn't provide ApiError with error information

---

templates/libraries/okhttp-gson/pojo.mustache

During the OpenAPI generation, a deprecated property (ie `recurringDetailReference`) only generates a deprecated getter, while the model attribute, the setter method and the builder method are not deprecated.
This PR adds the @Deprecated annotation where it is applicable
**Note**: the same correction has been merged in the OpenAPI Generator, see [PR 15287](https://github.com/OpenAPITools/openapi-generator/pull/15287)

Model generation: deprecate build and setter methods

---

src/main/java/com/adyen/constants/ApiConstants.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java
src/main/java/com/adyen/model/RequestOptions.java

Adding `x-requested-verification-code` in `RequestOptions` model to test verification/KYC scenarios
**Fixed issue**:  #1031

Adding x-requested-verification-code in request options

---

src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
src/main/java/com/adyen/serializer/SaleToAcquirerDataSerializer.java

Adds missing deserialization of SaleToAcquirerData for SaleToPOIResponses, e.g. when using the payment provider Twint in Switzerland
* Base 64 Encodeded SaleToAcquirerData was parsed correctly. 
**Fixed issue**:  #[1037](https://github.com/Adyen/adyen-java-api-library/issues/1037)

Add SaleToAcquirerDataSerializer deserialisation

---

README.md
src/main/java/com/adyen/notification/BankingWebhookHandler.java
src/test/java/com/adyen/WebhookTest.java

Implemented @michaelpaul's feedback regarding the webhooks. This way merchants get use the Optional fields to check the webhook type.

[ITT-572] Process webhooks with Optional field

---

src/main/java/com/adyen/service/TerminalLocalAPI.java
src/main/java/com/adyen/terminal/security/NexoCrypto.java
src/test/java/com/adyen/NexoCryptoTest.java
src/test/java/com/adyen/TerminalLocalAPITest.java

The Adyen Java API library currently derives a key for every single local terminal API request instead of caching it. This has a performance impact, especially when using the library on Android devices or Adyen Android terminals
All unit tests.
**Fixed issue**:  ITT-599

[ITT-599] Implement caching of NexoDerivedKey for TerminalLocalAPI.

---

.github/workflows/javaci.yml
src/test/java/com/adyen/BaseTest.java

This branch adds Java 17 support to the CI, so our library can be compiled with the JDK 17 (even if we stay 11 compatible).
None yet, to be done.

Java 17 and Java 20 CI support

---

.github/workflows/javaci.yml
src/main/java/com/adyen/ApiKeyAuthenticatedService.java
src/test/java/com/adyen/BaseTest.java
src/test/java/com/adyen/WebhookTest.java

Maven is not able to package with java 17 as library still used deprecated Long initializer and some minor other issues. This PR fixes that so everyone can package the library and test it using java 17.

Additional cleanup to support java17

---

src/main/java/com/adyen/model/checkout/CheckoutPaymentMethod.java
src/main/java/com/adyen/model/checkout/PaymentResponseAction.java
src/test/java/com/adyen/CheckoutTest.java
templates/libraries/jersey3/anyof_model.mustache
templates/libraries/jersey3/oneof_model.mustache

Bring back the from/toJson methods in oneOf/AnyOf classes. This was removed by accident as the jersey3 framework did not use these classes and it was added manually in the templates. Tested by generating checkout specs and adding UT for CheckoutPaymentMethod.

Bring back from/toJson methods in oneOf and anyOf classes

---

src/main/java/com/adyen/model/balanceplatform/BankAccountIdentificationValidationRequestAccountIdentification.java
src/main/java/com/adyen/model/balanceplatform/Card.java
src/main/java/com/adyen/model/balanceplatform/CardInfo.java
src/main/java/com/adyen/model/balanceplatform/PaymentInstrumentBankAccount.java
src/main/java/com/adyen/model/balanceplatform/UpdateSweepConfigurationV2.java
src/main/java/com/adyen/model/balanceplatform/VerificationDeadline.java
src/main/java/com/adyen/model/checkout/CheckoutPaymentMethod.java
src/main/java/com/adyen/model/checkout/PaymentResponseAction.java
src/main/java/com/adyen/model/legalentitymanagement/BankAccountInfoAccountIdentification.java
src/main/java/com/adyen/model/management/ScheduleTerminalActionsRequestActionDetails.java
src/main/java/com/adyen/model/transfers/BankAccountV3AccountIdentification.java
src/main/java/com/adyen/model/transfers/HKLocalAccountIdentification.java
src/main/java/com/adyen/model/transfers/Transaction.java
src/main/java/com/adyen/model/transfers/Transfer.java
src/test/java/com/adyen/CheckoutTest.java
templates/libraries/jersey3/oneof_model.mustache

With the fix done for CronSweepSchedule there is no need anymore for soft validation in oneOf's. I removed the custom jsonMapper with strict validation and instead opted again for the default value as every oneOf can now be validated on type solely.

Removed strict validation and regenerate oneOfs

---

src/main/java/com/adyen/service/checkout/ClassicCheckoutSdkApi.java
src/main/java/com/adyen/service/checkout/ModificationsApi.java
src/main/java/com/adyen/service/checkout/OrdersApi.java
src/main/java/com/adyen/service/checkout/PaymentLinksApi.java
src/main/java/com/adyen/service/checkout/PaymentsApi.java
src/main/java/com/adyen/service/checkout/RecurringApi.java
src/main/java/com/adyen/service/checkout/UtilityApi.java
templates/libraries/jersey3/api.mustache

The implementation of `createBaseURL(...)` forces us to use HTTPS, but we need our app servers to use HTTP and let our service mesh catch and encrypt the outgoing requests before they leave our system (transparent from your point of view, the requests will always reach you through HTTPS).
One backward-compatible approach could be as proposed here: allow the `baseURL` to be passed to the constructor directly. It would greatly simplify our usage, given we currently have to hack around by overriding `createBaseURL(...)` thanks to its `protected` visibility.
Let me know what you think.

Allow passing baseURL directly when constructing API services

---

src/main/java/com/adyen/service/checkout/RecurringApi.java
src/test/java/com/adyen/CheckoutTest.java

The deleteTokenForStoredPaymentDetails should be void based on the [documentation](https://docs.adyen.com/api-explorer/Checkout/70/delete/storedPaymentMethods/_storedPaymentMethodId_) 
Modify the tests

Convert to void the recurring api deleteTokenForStoredPaymentDetails

---

templates/libraries/jersey3/pojo.mustache

Update the `pojo.mustache` to add description  with param on models setters for javadoc.
Generate the models and the setters has javadoc based on the openapi specs

Update fields with javadoc description from open api specs

---

src/main/java/com/adyen/model/notification/NotificationRequestItem.java

Minor change, adding the EXPIRE notification type to the NotificationRequestItem constants for import on our side when treating expire notifications
As seen on the [documentation](https://docs.adyen.com/development-resources/webhooks/webhook-types/#event-codes)

misc(notification): Add expire code to constants

---

.github/workflows/stale.yml

updated stale.yml to ignore pull requests.
unset the default checks by setting them to -1
only consider pr's with the labels 'awaiting-changes', 'blocked', 'work-in-progress', 'awaiting-upstream'.
removing the pr label when updated

stalebot fix

---

pom.xml

Downgraded Jackson dependencies in pom.xml to version 2.12.7 to add support for Android 7. 
Unit-tests did not fail. 
Creating a pull request to check if other tests are successful too.

downgraded Jackson dependencies

---

pom.xml
src/main/java/com/adyen/model/terminal/SaleToAcquirerData.java
src/main/java/com/adyen/terminal/security/NexoCrypto.java
src/test/java/com/adyen/serializer/SaleToAcquirerDataSerializerTest.java

Commons-codec provides Base64 encoding and decoding support for Android 7
- added import in SaleToAcquirerData.java in Terminal API and adjusted methods
- added dependency in pom.xml
- adjusted unit-test SaleToAcquirerDataSerializerTest.java.

Downgrade dependency Base64 for terminal

---

templates/libraries/jersey3/api_summary.mustache
templates/libraries/jersey3/api_summary_overload.mustache
templates/libraries/jersey3/pojo.mustache

The library deprecates correctly the attributes/endpoints that are marked as deprecated in the OpenAPI spec files.  
This PR improves the existing code by adding the additional information (`deprecatedInVersion`, `deprecatedMessage`) in the Javadoc.
Formatting has also been improved removing unnecessary extra lines after getter/setter methods.

Improve deprecation information adding deprecatedInVersion and deprecatedMessage in the Javadoc

---

templates/libraries/jersey3/pojo.mustache

Escaping class/attribute description is breaking the Java API library pipeline as the generated javadoc contains the character `>`, which is not allowed and should be escaped.
This PR revert partially the changes introduced in PR #1367

Skip escaping descriptions in mustache templates

---

.github/workflows/codeql-analysis.yml

CodeQL workflows runs on `push`, `pull_request` and `cron`.
This PR updates the workflow configuration to run on `cron` only.

Run CodeQL analysis on cron job only

---

pom.xml
src/main/java/com/adyen/httpclient/AdyenHttpClient.java
src/main/java/com/adyen/terminal/serialization/ByteArrayToBase64TypeAdapter.java
src/main/java/com/adyen/util/HMACValidator.java
src/test/java/com/adyen/LegalEntityManagementTest.java
src/test/java/com/adyen/PaymentTest.java
src/test/java/com/adyen/serializer/ByteArrayToStringAdapterTest.java

In order to support android versions 7  and higher we decided to change `java.util.Base64` in favour of the `org.apache.commons.codec.binary.Base64` library. This PR serves to finish this migration.

Finish migrating java util base64 to apache commons

---

src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java

Since version v29.1.0 of your SDK, you're relying on Apache HttpClient v5.4 ([diff](https://github.com/Adyen/adyen-java-api-library/compare/v29.0.0...v29.1.0)).
This version of HttpClient doesn't play well with Istio: https://github.com/istio/istio/issues/53239
A way to fix this is to disable the protocol upgrade, which HttpClient allows. This is what this PRs proposes.
It's also the recommended approach by Spring Boot: https://github.com/spring-projects/spring-boot/issues/43139 (while waiting for https://github.com/envoyproxy/envoy/issues/36305).

feat(tls): allow disabling protocol upgrade

---

src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java

Reverts Adyen/adyen-java-api-library#1409

Revert "feat(tls): allow disabling protocol upgrade"

---

src/main/java/com/adyen/model/nexo/CustomerOrder.java

Add missing field [SaleReferenceID](https://docs.adyen.com/api-explorer/terminal-api/1/post/payment#request-PaymentData-CustomerOrder-SaleReferenceID) in Nexo `CustomerOrder` class

Nexo CustomerOrder: add SaleReferenceID field

---

src/main/java/com/adyen/service/resource/Resource.java
src/test/java/com/adyen/service/ResourceTest.java

When an error occurs and the response body isn't JSON (e.g. a misconfiguration of the base path triggering an HTML error page as a response), the code swallows the original error and instead throws a parsing exception.
This PR ensures parsing exceptions are ignored so that the original issue remains available.

fix(exception): better handle non-JSON response bodies

---

.github/workflows/javaci.yml
.github/workflows/sonarcloud.yml

This PR introduces several improvements to the GitHub workflows for Java CI and Sonarcloud GitHub workflows. The changes aim to optimize the workflows, enhance security, and ensure that necessary steps are included for a smooth CI and release process.
**Changes**
- Combined checkout, build, test steps: ensured that the `java-test` job depends on the `java-check` job, avoiding redundant checkout steps.
- Consistent naming: improved step names for better readability.
Successfully ran and verified all the GitHub workflow in a forked repo

Improve Github workflows

---

src/main/java/com/adyen/service/exception/ApiException.java
src/main/java/com/adyen/service/resource/Resource.java
src/test/java/com/adyen/BaseTest.java
src/test/java/com/adyen/service/ResourceTest.java
src/test/resources/mocks/response-validation-error-invalid-json.json

This PR improves the error handling by refactoring the code that creates the `ApiException`.
In the new approach, the API error (JSON) is parsed first to obtain all the error details, then the `ApiException` object is instantiated using a meaningful error message (instead of a default `HTTP Exception error` message.

Ovverride default ApiError message with the error message from the API response

---

src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java

This PR makes `connectionRequestTimeout` setting configurable.
It also renames the configuration setting `defaultKeepAlive` to `defaultKeepAliveMillis` (this is not a breaking change as the new property was created during the development of this release and no yet published).
Fix #1460

Configure HTTP Client connectionRequestTimeout

---

src/main/java/com/adyen/Config.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java
src/test/java/com/adyen/httpclient/ClientTest.java

PR that makes sure `User-Agent` header doesn't contain `null` when `applicationName` is undefined

Avoid null in User-Agent header

---

.github/workflows/javaci.yml

Update CI workflow to:
- run `on push` only on `main` branch (when a PR is merged)
- run `on pull_request` on `main`, SDK Automation Bot PRs and Release bumps

CI workflow: update to avoid uneccessary executions

---

pom.xml

The deploy to Maven Central was successful, but the pipeline [failed](https://github.com/Adyen/adyen-java-api-library/actions/runs/15701434786) because of timeout.
This PR updates the configuration of the GitHub action to wait until the package is `validated`. It will eventually be published after x minutes.

Maven Publishing Plugin: update configuration

---

src/main/java/com/adyen/httpclient/AdyenCustomRedirectStrategy.java
src/main/java/com/adyen/httpclient/AdyenHttpClient.java
src/test/java/com/adyen/httpclient/AdyenCustomRedirectStrategyTest.java

The Terminal API returns `308` response status when the incorrect region is used. The Java library handles the `308` by redirecting to the endpoint returned in the location header.
This PR introduces a validation that ensures the url is part of `adyen.com` or `adyenpayments.com`

Validate location header 308
